export const PersonalRaidsData = [
    {
        id: 0,
        name: "Magma Horror",
        size: "Personal",
        type: ["Underground","Beast"],
        timer: 24,
        magics: 1,
        cooldown: null,
        rarity: null,
        resources: ["Stamina"],
        notes_obtain: "Subterranean Depths quest bosses: Maraak the Impaler, Erakka-Sak, Wexxa the Worm-Tamer, Guilbert the Mad, Bellarius the Guardian",
        notes: "Faustus tells you that he's detected something in the magma, a strange aura as though some lurking monstrosity is nearby. He says it feels familiar...",
        art_thumb: 'Magma_horror_small.jpg',
        art_essence: 'Essence_magmahorror.png',
        tiers: [{
            difficulty: "Personal",
            maxHp: 200000,
        }]
    },
    {
        id: 1,
        name: "Dahrizon's General",
        size: "Personal",
        type: ["Undead"],
        art: '/memes/x2.jpg',
     },
     {
        id: 2,
        name: "Animated Armor Essence",
        size: "Personal",
        type: ["Construct"],
        timer: 12,
        magics: 1,        
        cooldown: 6,
        rarity: null,
        resources: ["Stamina"],
        notes_obtain: "Animated Armor quest boss",
        notes: null,
        art_thumb: null,
        art_essence: 'Essence_animarmor.png',
    },
    {
        id: 3,
        name: "Apocolocyntosised Axe Murderer Essence",
        size: "Personal",
        type: ["Orc"],
        timer: 12,
        magics: 1,        
        cooldown: 12,
        rarity: "Uncommon",
        resources: ["Stamina"],
        notes_obtain: "Nightmare Apocolocyntosised Axe Murderer (Mini Boss) in Sanguine Stories",
        notes: "Pumpkin Night is fun for children and murderous criminals alike. Until they run into you, that is, and cleave the heads from their shoulders (though you'll probably only do this to the latter group).",
        art_thumb: null,
        art_essence: 'Essence_apocolocyntosised_axe_murderer.png',
    },

    
];